services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    # command: sh -c "(hostname && echo 'Iniciando topics' && kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 2 --topic ventas) && /opt/bitnami/scripts/kafka/entrypoint.sh /run.sh"

  # database:
  #   image: bitnami/postgresql:12.10.0
  #   container_name: db-tarea
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRESQL_USER: postgres
  #     POSTGRESQL_PASSWORD: postgres
  #     POSTGRESQL_DATABASE: tarea
  #   restart: always
