DROP TABLE IF EXISTS carritos;
CREATE TABLE IF NOT EXISTS carritos(nombre VARCHAR(50), apellido VARCHAR(50), rut VARCHAR(50), correodueno VARCHAR(200), patente VARCHAR(10), premium INT, stock INT, ubicacion VARCHAR(10));
INSERT INTO carritos VALUES ('Jose','Jose','1-1','josejose@hola.com','Jose',1,100, '0');
INSERT INTO carritos VALUES ('Luis','Luis', '2-2','alb@hola.com','Luis',0,100, '0');
INSERT INTO carritos VALUES ('Alberto','Alberto', '3-3','AlbertoAlberto@hola.com','Alberto',1,100, '0');
INSERT INTO carritos VALUES ('Guillermo','Guillermo', '4-4','GuillermoGuillermo@hola.com','Guillermo',0,100, '0');
INSERT INTO carritos VALUES ('Pablo','Pablo', '5-5','PabloPablo@hola.com','Pablo',1,100, '0');
INSERT INTO carritos VALUES ('Diego','Diego', '6-6','DiegoDiego@hola.com','Diego',0,100, '0');
INSERT INTO carritos VALUES ('Claudio','Claudio', '7-7','ClaudioClaudio@hola.com','Claudio',0,100, '0');
INSERT INTO carritos VALUES ('Tomas','Tomas', '8-8','TomasTomas@hola.com','Tomas',0,100, '0');
